name: Publish to Docker Hub

on:
  push:
    branches:
      - main
  schedule:
   - cron: "0 0 * * *" # Runs every day at midnight to generate a new Docker image to capture upstream changes

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8,linux/s390x,linux/ppc64le
          push: true
          tags: dylanmtaylor/squid-network-proxy:latest
